default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  pool: 5
  port: 3306

development:
  <<: *default
  database: tipfortip

test:
  <<: *default
  database: tipfortip_test
