# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5e51ea6c30486e28508c5f39175bcccd5630164d6ead9def9c2f4ffc90a3cd7be4a0a6ce2ece2c55234c3ec79fa43dc04637ce788d8dcfd71d8a6b0b550d18

  facebook:
    client_id: 348319281870301
    client_secret: 01e1014adc5b175b3a87b9246928d879

  foursquare:
    client_id: RVJESU4WHCE2513FZJN4NSFHBXC5CCYNVNZYXL1O5A04LQOC
    client_secret: 20DMXZMMULIW0P1OW31FJ1YCGN35FXQSB3MNGQ2IVGALVAM3

  mandrill:
    # api_key: WhTh7dQ0FFUY4kN7IORhYw
    api_key: Q3JqUGlftN8Zi8Sro34-Xg

  twitter:
    client_id: 7MqKVrzQitJ8YKjlwuPR7vpV4
    client_secret: BCRzT4SAWiVPSu7WjCNLRZIR78kIrcQHRZ5xNuOoJMIjIUCiNI

  rollbar:
    access_token: f1bbe21eed9d4150b59c0a9ed63de318

  statsmix:
    api_key: <%= ENV['STATSMIX_API_KEY'] %>

test:
  secret_key_base: 9f87e51cdf67282792db94dfe623cbe4322a312970aeaac077aa88ce7d17fb1a022b3e061642bb026c6b40ac35dd65932668097e53d94c9aeb9767968dfe0e65

  facebook:
    client_id: 'fake_client_id'
    client_secret: 'fake_client_secret'

  foursquare:
    client_id: 'fake_client_id'
    client_secret: 'fake_client_secret'

  mandrill:
    api_key: fake

  twitter:
    client_id: 'fake_client_id'
    client_secret: 'fake_client_secret'

  rollbar:
    access_token: "fake"

  statsmix:
    api_key: "fake"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  facebook:
    client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
    client_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>

  foursquare:
    client_id: <%= ENV["FOURSQUARE_CLIENT_ID"] %>
    client_secret: <%= ENV["FOURSQUARE_CLIENT_SECRET"] %>

  mandrill:
    api_key: <%= ENV["MANDRILL_API_KEY"] %>

  twitter:
    client_id: <%= ENV["TWITTER_CLIENT_ID"] %>
    client_secret: <%= ENV["TWITTER_CLIENT_SECRET"] %>

  rollbar:
    access_token: <%= ENV["ROLLBAR_ACCESS_TOKEN"] %>

  statsmix:
    api_key: <%= ENV['STATSMIX_API_KEY'] %>
